#!/bin/sh
HTTP_ACCESS_USERNAME=$1
# HTTP_ACCESS_PASSWORD=$2
echo $HTTP_ACCESS_PASSWORD
# HTTP_ACCESS_PASSWORD =$HTTP_ACCESS_PASSWORD
sh -c '/bin/echo -e "$2\n$2" "$1"' create-file $HTTP_ACCESS_USERNAME $HTTP_ACCESS_PASSWORD
